version: "3.8"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: fakeroot

  web:
    build:
      context: ../../../compose/artifacts/c05-compose01/
    environment:
      DB_USER: root
      DB_PASS: fakeroot
      DB_HOST: db
      DB: db
    ports:
      - "8100:80"
    volumes:
      - ../../../compose/artifacts/c05-compose01/src/:/var/www/html/
    depends_on:
      - db