# compose docker container using supplied Dockerfile
version: '3.1'

services:
  3musketeers:
    platform: linux/amd64
    container_name: 3musketeers
    build: .
    restart: always
    env_file: .env
    volumes:
      - type: bind
        source: .
        target: /opt/app/
    working_dir: /opt/app
