version: '3.4'

services:

 web:
    build: .
    ports:
        - 8100:80
    environment:
        DB_USER: root
        DB_PASS: thisisasecurepassword
        DB_HOST: db
        DB: db
    volumes:
        - ./src:/var/www/html
        

 db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: thisisasecurepassword
