Admin:
  - '@caiocezart'
  - '@denstorti'
  - '@kikobr82'

2020-Feb:
  - '@andreazzabr'
  - '@carineoliveira'
  - '@christina-roperto'
  - '@deniseddi'
  - '@drii-cavalcanti'
  - '@Faria-Marcio'
  - '@hsy3418'
  - '@lgothelipe'
  - '@luizfds'
  - '@marcioanatrielo'
  - '@starkmatt'

2020-Jun:
  - '@alanlima'
  - '@danielvca'
  - '@fabioacp'
  - '@feernandobraga'
  - '@frdvo'
  - '@gepifanio'
  - '@gpavelar'
  - '@igorjosesantos'
  - '@jayanath'
  - '@mail2kvanitha'
  - '@mfreitassm'
  - '@mrcsmonteiro'
  - '@nimmi89'
  - '@obrientimothya'
  - '@shahriar048'
  - '@zarajoy'