version: '3.8'
services:
  db_service:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dojo
      MYSQL_DATABASE: dojo
      MYSQL_USER: dojo
      MYSQL_PASSWORD: dojo
  
  web_service:
    build: ~/Documents/academy/classes/03class/compose/artifacts/c05-compose01
    ports:
      - '8100:80'
    environment:
      DB_USER: dojo
      DB_PASS: dojo
      DB_HOST: dojo
      DB_NAME: dojo
    volumes:
      - ~/Documents/academy/classes/03class/compose/artifacts/c05-compose01/src/:/var/www/html/
  