name: lgothelipe-comment-pr
on: 
    pull_request: 
        paths: 
        - lgothelipe/**
jobs:
    comment:
        runs-on: ubuntu-latest
        steps:
            - uses: mshick/add-pr-comment@v1
              with:
                  repo-token: ${{ secrets.LG_GITHUB_TOKEN }}
                  message: Well done ${{ secrets.LG_MY_NAME }} ! This is a nice PR
                  allow-repeats: false
