FROM alpine:3.9.5
WORKDIR tmp
RUN wget https://releases.hashicorp.com/terraform/0.12.23/terraform_0.12.23_linux_amd64.zip && \
    unzip ./terraform_0.12.23_linux_amd64.zip -d /usr/local/bin/ && \
    rm -rf ./terraform_0.12.23_linux_amd64.zip
CMD terraform -v