# Define the base image used to build our new image.
FROM httpd:2.4.41-alpine
# Create ARGs which will NOT persist in final image. 
ARG DST=/usr/local/apache2/htdocs/
ARG FILE=index.html
# Copy the file "index.html" from src to dst. 
COPY $FILE $DST 
# Export port 80 using the TCP protocol. 
EXPOSE 80/tcp