variable projectname {type = string}
variable az {type = list}
variable inst_type {type = string}
variable inst_key {type = string}
variable ami_id {type=string}
variable asg_desired_capac {type=string}
variable asg_max_size {type=string}
variable asg_min_size {type=string}
variable efs_id {type = string}
variable rds_endpoint {type = string}
variable alb_sg {type = string}
variable vpc_id {type = string}
variable db_host_arn {type = string}
variable db_user_arn {type = string}
variable db_passowrd_arn {type = string}
variable db_name_arn {type = string}
variable pub_sub1 {type = string}
variable pub_sub2 {type = string}
variable target_group_arn {type = string}
variable containerimage {type=string}
variable retention_in_days {type=number}