# docker-compose will use an .env file by default, must be in present working directory
# example .env file:
# DB_PASS=verysecurepassword
#
# Ensure the supplied php files are in /src in the present working directory 
# Also ensure the supplied Dockerfile is in the present working directory

version: '3.1'

services:
  db:
    platform: linux/amd64
    container_name: db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: php
    ports:
      - 3306:3306
  web:
    build: .
    environment:
      DB_USER: root
      DB_PASS: ${DB_PASS}
      DB_HOST: db
      DB: php
    ports:
      - 8100:80
    volumes: 
      - ./src:/var/www/html/
