version: "3.8"

services:

  web:
      build: .
      ports:
        - "8100:80"
      networks:
        - front-end
        - back-end
      volumes:
        - ./src:/var/www/html
      env_file:
        - '.web.env'
      deploy:
        resources:
          limits:
            cpus: '0.50'
            memory: 50M
          reservations:
            cpus: '0.25'
            memory: 20M
      depends_on: 
      - db


  db:
      image: "mysql:5.7"
      ports:
        - "3306:3306"
      networks:
        - back-end
      env_file:
        - '.db.env'
      deploy:
        resources:
          limits:
            cpus: '0.50'
            memory: 300M
          reservations:
            cpus: '0.25'
            memory: 200M

networks:
  front-end:
  back-end:
