version: '3.8'

services:

    db:
      image: mysql:5.7
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: db
          MYSQL_USER: user
          MYSQL_PASSWORD: secret

    web:
        build: .
        ports:
            - "8100:80"
        volumes:
        - ./src:/var/www/html
        environment:
            DB_USER: user
            DB_PASS: secret
            DB_HOST: db
            DB_NAME: db