version: '3.3'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123

  web:
    build: .
    depends_on:
      - db
    volumes: 
      - ./src:/var/www/html:rw
    ports:
      - 8100:80 
    restart: always
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASS: admin123
      DB: db
    