version: '3'
services:
  web:
    build: .
    restart: always
    volumes:
      - ./src:/var/www/html
    ports:
      - 8100:80
    environment:
      DB_USER: root
      DB_PASS: mypassword
      DB_HOST: db
      DB: db
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword