version: '3'
services:
  web:
    build: .
    ports:
      - "8100:80"
    environment:
      DB_USER: christina
      DB_PASS: pass321
      DB_HOST: db
      DB: c05-compose01
    volumes:
        - ./var/www/html/src:/var/www/html/

  db:
    image: "mysql:5.7"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: christina
      MYSQL_PASSWORD: pass321
      MYSQL_DATABASE: c05-compose01
    ports:
      - "3306:3306"