version: '3'
services:
  web:
    build: .
    ports:
      - "8100:80"
    environment:
      DB_USER: testuser
      DB_PASS: testpass
      DB_HOST: db
      DB: dbname
    volumes:
      - ./src:/var/www/html/
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: testpassroot
      MYSQL_DATABASE: dbname
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass 
