FROM ubuntu:18.04
WORKDIR tmp
RUN apt-get update && apt-get install -y \
    curl \
 && rm -rf /var/lib/apt/lists/*
RUN curl -k http://apache.mirror.serversaustralia.com.au//httpd/httpd-2.4.51.tar.gz -o /tmp/httpd-2.4.51.tar.gz && \
    tar xzvf /tmp/httpd-2.4.51.tar.gz && \
    rm -rf /tmp/httpd-2.4.51.tar.gz
