---
version: "3"
services:
  terraform:
    image: hashicorp/terraform:0.12.29
    working_dir: /app
    volumes:
      - ${PWD}:/app:z
    env_file:
      - .env
  aws:
    image: amazon/aws-cli:2.0.44
    env_file:
      .env
