---
version: '3'

services:
  db:
    image: mysql:5.7
    env_file:
      - db.env
    ports:
      - "3306:3306"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - web.env
    depends_on:
      - db
    volumes:
      - ./src/:/var/www/html/
    ports:
      - "8100:80"
