# Define the base image used to build our new image
FROM alpine:latest
# Create ENV variables for firstname and lastname. We are able to modify this upon execution of the container. 
ENV fname="null"
ENV lname="null"
# Print the message output in the terminal window. 
CMD echo "Hello $fname $lname!" 