#Final image is based from httpd:2.4.41-alpine
FROM httpd:2.4.41-alpine
#Copy the file classes/03class/docker/artifacts/c03-docker02/index.html into the folder /usr/local/apache2/htdocs/
COPY classes/03class/docker/artifacts/c03-docker02/index.html /usr/local/apache2/htdocs/

