name: comment to all my PR with standard message

on: [pull_request]

jobs:
  my-job:
    name: my job
    runs-on: ubuntu-latest
    steps:
    - name: print a greeting
      env:
        MY_NAME: Caio
      run: |
        echo Hello $MY_NAME
