on: 
  merge:
    paths:
    - 'scripts/tf/github.com/**/*'
    
name: GH Terraform Apply
jobs:
  gh-terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: hashicorp/setup-terraform@v1

    - name: Run Terraform
      run: |
        cd scripts/tf/github.com
        terraform init
        terraform apply -auto-approve -input=false
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_github_token: ${{ secrets.GH_TOKEN }}