on:
  push:
    branches:
      - master
    paths:
    - 'scripts/tf/github.com/**/*'
    
name: GH Terraform Apply
jobs:
  gh-terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Run Terraform apply
      run: make gh-apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_github_token: ${{ secrets.GH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
