name: Review Exercises
on:
  pull_request:
    paths:
    - 'students/**/*'

jobs:
  review-exercises:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: 'csv'
          filters: |
            git03:
              - 'students/**/git03/**/*'
            git04:
              - 'students/**/git04/**/*'
      
      - name: Check if exercise is latest version
        id: validate
        if: steps.changes.outputs.git04 == 'true'
        run: |
          python3 reviewer/exercises/validate.py \
            ${{steps.changes.outputs.git03_files}} \
            ${{steps.changes.outputs.git04_files}}
          ERROR=$(cat error)
          EXERCISE=$(cat exercise)
          echo "ERROR=$ERROR" >> $GITHUB_OUTPUT
          echo "exercise=$EXERCISE" >> $GITHUB_OUTPUT
          
          if [ $ERROR = "true" ]; then
            echo "Multiple exercises being changed, please amend your PR to submit one exercise at a time";
          fi;
      
      - name: Check steps outputs
        run: |
          echo ${{steps.validate.outputs.error}}

      - name: git04 - Review exercise
        uses: addnab/docker-run-action@v3
        if: steps.changes.outputs.git04 == 'true'
        with:
            image: devopsacademy/reviewer:git04-latest
            options: -v ${{ github.workspace }}:/exercise
