name: Review Exercises
on:
  pull_request:
    paths:
    - 'students/**/*'

jobs:
  review-exercises:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: 'csv'
          filters: |
            git04:
              - 'students/**/git04/**/*'
            git03:
              - 'students/**/git03/**/*'
      
      - name: Check if exercise is latest version
        id: validate
        if: steps.changes.outputs.git04 == 'true'
        run: |
          python3 reviewer/exercises/validate.py ${{steps.changes.outputs.git04_files}}
          ls
          echo "ERROR=$(cat error)" >> $GITHUB_OUTPUT
          echo "exercise=$(cat exercise)" >> $GITHUB_OUTPUT
          if [ $(cat ERROR) ]; then
            echo "Multiple exercises being changed, please amend your PR to submit one exercise at a time";
          fi;
      
      - name: Check steps outputs
        if: steps.validate.outputs.some_output == 'test'
        run: |
          echo ${{steps.validate.outputs.exercise}}

      - name: git04 - Review exercise
        uses: addnab/docker-run-action@v3
        if: steps.changes.outputs.git04 == 'true'
        with:
            image: devopsacademy/reviewer:git04-latest
            options: -v ${{ github.workspace }}:/exercise
