name: Review Exercises
on:
  pull_request:
    paths:
    - 'students/**/*'

jobs:
  review-exercises:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: json
          filters: |
            git03:
              - 'students/**/git03/**/*'
            git04:
              - 'students/**/git04/**/*'

      # - name: Check multiple exercises submitted outputs
      #   run: |
      #     echo ${{steps.validate.outputs.error}}
      
      # - name: Get exercises metadata
      #   id: validate
      #   if: steps.changes.outputs.git04 == 'true'
      #   run: |
      #     python3 reviewer/exercises/validate.py ${{steps.changes.outputs.changes}}
      #     MULTIPLE=$(cat error)
      #     EXERCISE=$(cat exercise)
      #     echo "multiple=$MULTIPLE" >> $GITHUB_OUTPUT
      #     echo "exercise=$EXERCISE" >> $GITHUB_OUTPUT
      
      - name: Debug
        run: |
          echo ${{ toJson(steps.changes.outputs.changes) }}
          echo "${{ toJson(steps.changes.outputs.changes) }}" | jq '. | length'

      - name: Check if multiple exercises have been submited
        run: |
          echo "${{ toJson(steps.changes.outputs.changes) }}" | jq '. | length' > $EXERCISES_CHANGED
          if $EXERCISES_CHANGED -gt 1;then
            echo "::error title='Multiple exercises found'::'Please submit only 1 exercise at a time.'";
            exit 1;
          fi;
      
      # - name: Check steps outputs
      #   run: |
      #     echo ${{steps.validate.outputs.error}}

      # - name: git04 - Review exercise
      #   uses: addnab/docker-run-action@v3
      #   if: steps.changes.outputs.git04 == 'true'
      #   with:
      #       image: devopsacademy/reviewer:git04-latest
      #       options: -v ${{ github.workspace }}:/exercise
