name: Reviewers Setup
on:
  pull_request:
    paths:
      - 'reviewer/exercises/**/*'
  push:
    branches:
      - 'master'
      - 'main'
    paths:
      - 'reviewer/exercises/**/*'

jobs:
  reviewers-setup:
    name: Get list of Reviewers to be build
    runs-on: ubuntu-latest
    outputs:
      exercises: ${{ steps.changes.outputs.changes }}
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: json
          filters: |
            git03:
              - 'reviewer/exercises/git03/**/*'
            git04:
              - 'reviewer/exercises/git04/**/*'
      
      - name: Debug
        run: |
          echo ${{ steps.changes.outputs.changes }}
      
      # - name: Get Reviewers metadata
      #   id: validate
      #   if: steps.changes.outputs.changes
      #   run: |
      #     echo "exercises=" >> $GITHUB_ENV
  
  reviewers-build-push:
    name: Build&Push Reviewer
    needs: [reviewers-setup]
    uses: devopsacademyau/academy/.github/workflows/reviewer-build-push.yaml@caio-exercises
    strategy:
      matrix:
        exercises: ${{ fromJson(needs.reviewers-setup.outputs.exercises) }}
    with:
      exercise: ${{ matrix.exercises }}
      ref: ${{ github.event_name }}
    secrets: inherit

  # call-reviewer-build-push-release:
  #   if: ${{ github.event_name == 'push' }}
  #   needs: [reviewers-setup]
  #   uses: devopsacademyau/academy/.github/workflows/reviewer-build-push.yaml@caio-exercises
  #   strategy:
  #     matrix:
  #       exercises: ${{needs.reviewers-setup.outputs.exercises}}
  #   with:
  #     exercise: ${{ matrix.exercises }}
  #     image_prefix: ''
  #     image_dockerfile: ./reviewer/Dockerfile.python
  #   secrets: inherit
