name: Review Exercises
on:
  pull_request:
    paths:
    - 'students/**/*'

jobs:
  review-exercises:
    name: Review Exercises
    runs-on: ubuntu-latest
    env:
      REVIEWER_FOLDER: reviewer
      STUDENTS_FOLDER: students
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: json
          filters: |
            git03:
              - '${{ env.STUDENTS_FOLDER }}/**/git03/**/*'
            git04:
              - '${{ env.STUDENTS_FOLDER }}/**/git04/**/*'
      
      # - name: Debug
      #   run: |
      #     GITHUB_ACTOR=${{ github.actor }}
      #     EXERCISE=$(echo "${{ toJson(steps.changes.outputs.changes) }}" | jq -r '.[0]')
      #     LATEST_VERSION=$(cat ${{ env.REVIEWER_FOLDER }}/exercises/$EXERCISE/config.json | jq -r '.version')
      #     STUDENT_VERSION=$(cat students/${{ github.actor }}/exercises/$EXERCISE/config.json | jq -r '.version')

      #     echo ${{ toJson(steps.changes.outputs.changes) }}
      #     echo "${{ toJson(steps.changes.outputs.changes) }}" | jq '. | length'
      #     echo EXERCISE=$EXERCISE
      #     echo LATEST_VERSION=$LATEST_VERSION
      #     echo STUDENT_VERSION=$STUDENT_VERSION
      #     echo GITHUB_ACTOR=$GITHUB_ACTOR

      - name: Check if student username exists
        run: |
          GITHUB_ACTOR=${{ github.actor }}
          if [[ ! -d "${{ env.STUDENTS_FOLDER }}/$GITHUB_ACTOR" ]];then
            echo "::error title='Student not found'::'Your Github username wasn't found under students/. Please make sure to use your Github username as student_name.'";
            exit 1;
          fi;

      - name: Check if multiple exercises have been submited
        run: |
          EXERCISES_CHANGED=$(echo "${{ toJson(steps.changes.outputs.changes) }}" | jq '. | length')
          if [ $EXERCISES_CHANGED -gt 1 ];then
            echo "::error title='Multiple exercises found'::'Please submit only 1 exercise at a time.'";
            exit 1;
          fi;
      
      - name: Check if exercise is on latest version
        id: check
        run:
          EXERCISE=$(echo "${{ toJson(steps.changes.outputs.changes) }}" | jq -r '.[0]')
          LATEST_VERSION=$(cat ${{ env.REVIEWER_FOLDER }}/exercises/$EXERCISE/config.json | jq -r '.version')
          STUDENT_VERSION=$(cat students/${{ github.actor }}/exercises/$EXERCISE/config.json | jq -r '.version')

          echo LATEST_VERSION=$LATEST_VERSION
          echo STUDENT_VERSION=$STUDENT_VERSION

          if [ $LATEST_VERSION != $STUDENT_VERSION ];then
            echo "::error title='Not latest version'::'Student exercise $EXERCISE version is $STUDENT_VERSION, not the latest ($LATEST_VERSION). Please update and submit again.'";
            exit 1;
          fi;

          echo "exercise=$EXERCISE" >> $GITHUB_OUTPUT

          echo "version=$STUDENT_VERSION" >> $GITHUB_OUTPUT

      - name: ${{ steps.check.outputs.exercise }}/${{ steps.check.outputs.version }} - Review exercise
        run: |
          IMAGE=devopsacademyau/reviewer:${{ steps.check.outputs.exercise }}-${{ steps.check.outputs.version }}
          docker run \
            --name reviewer \
            -v ${{ github.workspace }}/${{ env.STUDENTS_FOLDER }}/${{ github.actor}}/exercises/${{ steps.check.outputs.exercise }}/:/exercise \
             $IMAGE

          if [ $? -ne 0 ];then
          
            exit 1;
          fi;

          docker logs reviewer | grep "SUMMARY:" > output
          while read line; do
            echo "${line}" | sed 's/SUMMARY://' >> $GITHUB_STEP_SUMMARY
          done < output
