on:
  workflow_call:
    inputs:
      exercise:
        required: true
        type: string
      ref:
        required: true
        type: string

jobs:
  reviewers-build-push:
    runs-on: ubuntu-latest 
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
          
      - name: ${{ inputs.exercise }} PR - Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            devopsacademyau/reviewer
          tags: |
            type=ref,event=pr,prefix=${{ inputs.image_prefix }}
            type=semver,pattern={{major}}.{{minor}}

      - name: ${{ inputs.exercise }} - Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./reviewer
          file: ${{ inputs.image_prefix }}
          build-args: |
            EXERCISE=${{ inputs.exercise }}
          tags: ${{ steps.meta.outputs.tags }}