name: reviewer-publish
on:
  pull_request:
    paths:
    - 'students/**/*'

jobs:
  review-exercises:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            git04:
              - 'students/**/git04/**/*'
            git03:
              - 'students/**/git03/**/*'
      
      - name: Check if exercise is latest version
        if: steps.changes.outputs.git04 == 'true'
        run: |
          echo ::set-output name=some_output::"test"
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: steps.validate.outputs.some_output == 'test'
