on:
  workflow_call:
    inputs:
      exercise:
        required: true
        type: string

jobs:
  reviewers-build-push:
    name: Build ${{ inputs.exercise }}/${{ github.event_name }}
    runs-on: ubuntu-latest 
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      
      - name: Build tag name
        id: tag
        run: |
          VERSION=$(cat reviewer/exercises/${{ inputs.exercise }}/config.json | jq -r .version)
          SUFFIX=$(if [ ${{ github.event_name }} = "pull_request" ]; then echo "-pr-${{ github.event.number }}"; else echo ""; fi;)
          echo "tag=${{ inputs.exercise }}-$VERSION$SUFFIX" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./reviewer/exercises/${{ inputs.exercise }}
          tags: ${{ steps.tag.outputs.tag }}