name: Reviewers Setup
on:
  pull_request:
    paths:
    - 'reviewer/exercises/**/*'
  push:
    paths:
    - 'reviewer/exercises/**/*'

jobs:
  reviewers-setup:
    runs-on: ubuntu-latest
    outputs:
      exercises: ${{steps.changes.outputs.reviewers.changes}}
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: json
          filters: |
            reviewers:
            - 'reviewer/exercises/**/*'
      
      # - name: Get Reviewers metadata
      #   id: validate
      #   if: steps.changes.outputs.changes
      #   run: |
      #     echo "exercises=" >> $GITHUB_ENV
  
  call-reviewer-build-push:
    needs: [reviewers-setup]
    uses: devopsacademyau/academy/.github/workflows/reviewer-build-push.yaml@caio-exercises
    with:
      exercise: ${{needs.reviewers-setup.output.sexercises}}
      image_prefix: git04-pr-
      image_dockerfile: ./reviewer/Dockerfile.python
    secrets: inherit
