FROM httpd:2.4.41-alpine
ADD https://raw.githubusercontent.com/devopsacademyau/academy/master/classes/03class/docker/artifacts/c03-docker02/index.html /usr/local/apache2/htdocs/
RUN chmod 755 -R /usr/local/apache2/htdocs
EXPOSE 80